// <auto-generated />
namespace Lesson.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LessonOfClassRoomAddedForeingKeyClassRoomId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LessonOfClassRoomAddedForeingKeyClassRoomId));
        
        string IMigrationMetadata.Id
        {
            get { return "202011230830393_LessonOfClassRoomAddedForeingKeyClassRoomId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
